"""Adiciona sistema de ocorrências

Revision ID: 08e2f6ddb744
Revises: c4a33c536347
Create Date: 2025-06-28 01:24:54.663367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e2f6ddb744'
down_revision = 'c4a33c536347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocorrencia_tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocorrencia_tipo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocorrencia_tipo_nome'), ['nome'], unique=True)

    op.create_table('orgao_publico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('contato', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orgao_publico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orgao_publico_nome'), ['nome'], unique=True)

    op.create_table('ocorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ronda_id', sa.Integer(), nullable=False),
    sa.Column('relatorio_final', sa.Text(), nullable=False),
    sa.Column('data_ocorrencia', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('endereco_especifico', sa.String(length=255), nullable=True),
    sa.Column('ocorrencia_tipo_id', sa.Integer(), nullable=False),
    sa.Column('registrado_por_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ocorrencia_tipo_id'], ['ocorrencia_tipo.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ronda_id'], ['ronda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocorrencia_data_ocorrencia'), ['data_ocorrencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocorrencia_ocorrencia_tipo_id'), ['ocorrencia_tipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocorrencia_registrado_por_user_id'), ['registrado_por_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocorrencia_ronda_id'), ['ronda_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ocorrencia_status'), ['status'], unique=False)

    op.create_table('ocorrencia_orgaos',
    sa.Column('ocorrencia_id', sa.Integer(), nullable=False),
    sa.Column('orgao_publico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencia.id'], ),
    sa.ForeignKeyConstraint(['orgao_publico_id'], ['orgao_publico.id'], ),
    sa.PrimaryKeyConstraint('ocorrencia_id', 'orgao_publico_id')
    )
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ronda_supervisor_id'), ['supervisor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ronda_supervisor_id'))

    op.drop_table('ocorrencia_orgaos')
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocorrencia_status'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_ronda_id'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_registrado_por_user_id'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_ocorrencia_tipo_id'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_data_ocorrencia'))

    op.drop_table('ocorrencia')
    with op.batch_alter_table('orgao_publico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orgao_publico_nome'))

    op.drop_table('orgao_publico')
    with op.batch_alter_table('ocorrencia_tipo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocorrencia_tipo_nome'))

    op.drop_table('ocorrencia_tipo')
    # ### end Alembic commands ###
