"""Adicionar campos de qualidade à ronda

Revision ID: 309eb9666b91
Revises: c4a33c536347
Create Date: 2025-06-22 10:37:05.474665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309eb9666b91'
down_revision = 'c4a33c536347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        # Adicione as colunas como NULÁVEIS primeiro
        batch_op.add_column(sa.Column('is_incomplete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_duration_anomalous', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ronda_supervisor_id'), ['supervisor_id'], unique=False)

    # Preencher os valores existentes para FALSE (ou outro valor padrão desejado)
    op.execute("UPDATE ronda SET is_incomplete = FALSE WHERE is_incomplete IS NULL")
    op.execute("UPDATE ronda SET is_duration_anomalous = FALSE WHERE is_duration_anomalous IS NULL")

    with op.batch_alter_table('ronda', schema=None) as batch_op:
        # Altere as colunas para NOT NULL após preencher os valores
        batch_op.alter_column('is_incomplete', nullable=False, existing_type=sa.Boolean())
        batch_op.alter_column('is_duration_anomalous', nullable=False, existing_type=sa.Boolean())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ronda_supervisor_id'))
        batch_op.drop_column('is_duration_anomalous')
        batch_op.drop_column('is_incomplete')

    # ### end Alembic commands ###