"""remove_ronda_from_ocorrencia_add_colaboradores_and_condominio

Revision ID: 49348b851951
Revises: ae3e50b8cc76
Create Date: 2025-06-29 23:01:20.771223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49348b851951'
down_revision = 'ae3e50b8cc76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condominio_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ocorrencia_condominio_id'), ['condominio_id'], unique=False)
        batch_op.create_foreign_key(None, 'condominio', ['condominio_id'], ['id'])

    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.alter_column('condominio_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.alter_column('condominio_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ocorrencia_condominio_id'))
        batch_op.drop_column('condominio_id')

    # ### end Alembic commands ###
