"""Cria tabela RondaSegmento e associa a Ronda

Revision ID: 54ff54303b33
Revises: 309eb9666b91
Create Date: 2025-06-22 12:18:36.255294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ff54303b33'
down_revision = '309eb9666b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ronda_segmento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ronda_id', sa.Integer(), nullable=False),
    sa.Column('inicio_dt', sa.DateTime(), nullable=False),
    sa.Column('termino_dt', sa.DateTime(), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('vtr', sa.String(length=50), nullable=True),
    sa.Column('is_incomplete_segment', sa.Boolean(), nullable=False),
    sa.Column('is_duration_anomalous_segment', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ronda_id'], ['ronda.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ronda_segmento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ronda_segmento_ronda_id'), ['ronda_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda_segmento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ronda_segmento_ronda_id'))

    op.drop_table('ronda_segmento')
    # ### end Alembic commands ###
