"""Permite nulos em inicio_dt e termino_dt de RondaSegmento

Revision ID: 6f22b151fd64
Revises: 54ff54303b33
Create Date: 2025-06-22 12:27:59.821203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f22b151fd64'
down_revision = '54ff54303b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda_segmento', schema=None) as batch_op:
        batch_op.alter_column('inicio_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda_segmento', schema=None) as batch_op:
        batch_op.alter_column('inicio_dt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
