"""Adiciona campo turno_ronda e atualiza relacao de condominio em Ronda

Revision ID: 6f635bf00a2b
Revises: aa2c47c6d5cc
Create Date: 2025-06-11 11:14:54.131888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite # Importe sqlite se for necessário para tipos específicos, mas geralmente não é para FKs


# revision identifiers, used by Alembic.
revision = '6f635bf00a2b'
down_revision = 'aa2c47c6d5cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condominio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('turno_ronda', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_ronda_condominio_id'), ['condominio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ronda_data_plantao_ronda'), ['data_plantao_ronda'], unique=False)
        batch_op.create_index(batch_op.f('ix_ronda_turno_ronda'), ['turno_ronda'], unique=False)
        batch_op.create_index(batch_op.f('ix_ronda_user_id'), ['user_id'], unique=False)

        # ADIÇÃO DO NOME EXPLÍCITO PARA A FOREIGN KEY
        batch_op.create_foreign_key(
            'fk_ronda_condominio_id_condominio',  # Nome explícito para a foreign key
            'condominio',
            ['condominio_id'],
            ['id']
        )
        batch_op.drop_column('condominio') # Remove a coluna antiga 'condominio' (string)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('condominio', sa.VARCHAR(length=150), nullable=True)) # Recria a coluna original
        
        # USA O NOME EXPLÍCITO DA FOREIGN KEY CRIADA NO UPGRADE PARA DELETAR
        batch_op.drop_constraint('fk_ronda_condominio_id_condominio', type_='foreignkey')
        
        batch_op.drop_index(batch_op.f('ix_ronda_user_id'))
        batch_op.drop_index(batch_op.f('ix_ronda_turno_ronda'))
        batch_op.drop_index(batch_op.f('ix_ronda_data_plantao_ronda'))
        batch_op.drop_index(batch_op.f('ix_ronda_condominio_id'))
        batch_op.drop_column('turno_ronda')
        batch_op.drop_column('condominio_id')

    # ### end Alembic commands ###