"""Adiciona supervisor_id na Ronda e relacionamento com User (com nomes de FK)

Revision ID: 7e6825f2be26
Revises: d6c548250e21
Create Date: 2024-07-29 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6825f2be26'
down_revision = 'd6c548250e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ronda_supervisor_id', 'user', ['supervisor_id'], ['id'])
        # Remova ou ajuste esta linha se você não tinha uma coluna 'status' na Ronda
        # batch_op.alter_column('status',
        #            existing_type=sa.VARCHAR(length=50),
        #            nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Adiciona a coluna como nullable primeiro
        batch_op.add_column(sa.Column('is_supervisor', sa.Boolean(), nullable=True))
    
    # ATUALIZA LINHAS EXISTENTES com um valor padrão (False)
    op.execute('UPDATE "user" SET is_supervisor = FALSE WHERE is_supervisor IS NULL')

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Altera a coluna para NOT NULL depois de preencher os valores nulos
        batch_op.alter_column('is_supervisor',
                   existing_type=sa.Boolean(),
                   nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_supervisor')

    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ronda_supervisor_id', type_='foreignkey')
        batch_op.drop_column('supervisor_id')
        # Remova ou ajuste esta linha se você não tinha uma coluna 'status' na Ronda
        # batch_op.alter_column('status',
        #            existing_type=sa.VARCHAR(length=50),
        #            nullable=True)

    # ### end Alembic commands ###