"""Adiciona supervisor_id na Ronda e relacionamento com User (com nomes de FK)

Revision ID: 7e6825f2be26
Revises: d6c548250e21
Create Date: 2025-06-16 16:05:56.129507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6825f2be26'
down_revision = 'd6c548250e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ronda_supervisor_id'), ['supervisor_id'], unique=False)
        batch_op.create_foreign_key('fk_ronda_supervisor_id', 'user', ['supervisor_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_supervisor', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_supervisor')

    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ronda_supervisor_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ronda_supervisor_id'))
        batch_op.drop_column('supervisor_id')

    # ### end Alembic commands ###
