"""Adiciona tabela de escala de supervisores

Revision ID: 85560bbf5ca0
Revises: 7e6825f2be26
Create Date: 2025-06-18 18:17:00.397379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85560bbf5ca0'
down_revision = '7e6825f2be26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escala_supervisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_turno', sa.String(length=50), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escala_supervisor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escala_supervisor_nome_turno'), ['nome_turno'], unique=True)
        batch_op.create_index(batch_op.f('ix_escala_supervisor_supervisor_id'), ['supervisor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('escala_supervisor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escala_supervisor_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_escala_supervisor_nome_turno'))

    op.drop_table('escala_supervisor')
    # ### end Alembic commands ###
