"""Adiciona tabela Colaborador

Revision ID: 984eaee96f94
Revises: e047996678be
Create Date: 2025-05-28 10:57:20.777139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984eaee96f94'
down_revision = 'e047996678be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colaborador_cargo'), ['cargo'], unique=False)
        batch_op.create_index(batch_op.f('ix_colaborador_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_colaborador_nome_completo'), ['nome_completo'], unique=False)

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('attempted_username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)

    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora_inicio', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('data_hora_fim', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('log_ronda_bruto', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('relatorio_processado', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('condominio', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('escala_plantao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_plantao_ronda', sa.Date(), nullable=True))
        batch_op.drop_column('log_ronda')
        batch_op.drop_column('data_hora')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('log_ronda', sa.TEXT(), nullable=False))
        batch_op.drop_column('data_plantao_ronda')
        batch_op.drop_column('escala_plantao')
        batch_op.drop_column('condominio')
        batch_op.drop_column('relatorio_processado')
        batch_op.drop_column('log_ronda_bruto')
        batch_op.drop_column('data_hora_fim')
        batch_op.drop_column('data_hora_inicio')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('attempted_username',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colaborador_nome_completo'))
        batch_op.drop_index(batch_op.f('ix_colaborador_matricula'))
        batch_op.drop_index(batch_op.f('ix_colaborador_cargo'))

    op.drop_table('colaborador')
    # ### end Alembic commands ###
