"""Adiciona tabela ProcessingHistory para o dashboard

Revision ID: aa2c47c6d5cc
Revises: 735fd4b237dc
Create Date: 2025-06-10 18:55:43.062948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa2c47c6d5cc'
down_revision = '735fd4b237dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('processing_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processing_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_history_processing_type'), ['processing_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_processing_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_processing_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_processing_history_processing_type'))

    op.drop_table('processing_history')
    # ### end Alembic commands ###
