"""Desacola Ronda de Ocorrencia e adiciona relacao com Colaborador

Revision ID: ae3e50b8cc76
Revises: 08e2f6ddb744
Create Date: 2025-06-29 20:27:56.018627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3e50b8cc76'
down_revision = '08e2f6ddb744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocorrencia_colaboradores',
    sa.Column('ocorrencia_id', sa.Integer(), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('ocorrencia_id', 'colaborador_id')
    )
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.drop_index('ix_ocorrencia_ronda_id')
        batch_op.drop_constraint('ocorrencia_ronda_id_fkey', type_='foreignkey')
        batch_op.drop_column('ronda_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ronda_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('ocorrencia_ronda_id_fkey', 'ronda', ['ronda_id'], ['id'])
        batch_op.create_index('ix_ocorrencia_ronda_id', ['ronda_id'], unique=True)

    op.drop_table('ocorrencia_colaboradores')
    # ### end Alembic commands ###
