"""Substitui EscalaSupervisor por EscalaMensal

Revision ID: c4a33c536347
Revises: 85560bbf5ca0
Create Date: 2025-06-18 19:22:03.864276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a33c536347'
down_revision = '85560bbf5ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escala_mensal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('nome_turno', sa.String(length=50), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'mes', 'nome_turno', name='_ano_mes_turno_uc')
    )
    with op.batch_alter_table('escala_mensal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_escala_mensal_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_escala_mensal_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_escala_mensal_nome_turno'), ['nome_turno'], unique=False)
        batch_op.create_index(batch_op.f('ix_escala_mensal_supervisor_id'), ['supervisor_id'], unique=False)

    with op.batch_alter_table('escala_supervisor', schema=None) as batch_op:
        batch_op.drop_index('ix_escala_supervisor_nome_turno')
        batch_op.drop_index('ix_escala_supervisor_supervisor_id')

    op.drop_table('escala_supervisor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escala_supervisor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_turno', sa.VARCHAR(length=50), nullable=False),
    sa.Column('supervisor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('escala_supervisor', schema=None) as batch_op:
        batch_op.create_index('ix_escala_supervisor_supervisor_id', ['supervisor_id'], unique=False)
        batch_op.create_index('ix_escala_supervisor_nome_turno', ['nome_turno'], unique=1)

    with op.batch_alter_table('escala_mensal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_escala_mensal_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_escala_mensal_nome_turno'))
        batch_op.drop_index(batch_op.f('ix_escala_mensal_mes'))
        batch_op.drop_index(batch_op.f('ix_escala_mensal_ano'))

    op.drop_table('escala_mensal')
    # ### end Alembic commands ###
