"""Adiciona campo total_rondas_no_log ao modelo Ronda

Revision ID: c76a8a00377c
Revises: 6f635bf00a2b
Create Date: 2025-06-11 13:49:03.718125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76a8a00377c'
down_revision = '6f635bf00a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_rondas_no_log', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_column('total_rondas_no_log')

    # ### end Alembic commands ###
