"""Adiciona campo para duracao total das rondas em minutos

Revision ID: d6c548250e21
Revises: dc7baae2314f
Create Date: 2025-06-12 15:50:14.945581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c548250e21'
down_revision = 'dc7baae2314f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracao_total_rondas_minutos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_column('duracao_total_rondas_minutos')

    # ### end Alembic commands ###
