"""Adiciona campos de eventos de log para Ronda

Revision ID: dc7baae2314f
Revises: c76a8a00377c
Create Date: 2025-06-11 14:12:25.709736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7baae2314f'
down_revision = 'c76a8a00377c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primeiro_evento_log_dt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_evento_log_dt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_column('ultimo_evento_log_dt')
        batch_op.drop_column('primeiro_evento_log_dt')

    # ### end Alembic commands ###
