"""Adiciona campos de aprovação e admin ao User com extend_existing

Revision ID: dfc453231baf
Revises: cc6705064f1e
Create Date: 2025-05-21 23:16:01.693328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc453231baf'
down_revision = 'cc6705064f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # MODIFICAÇÃO AQUI: Adicionado server_default=sa.false()
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.false()))
        
        # As colunas abaixo já estão corretas conforme o script gerado, pois são nullable=True
        batch_op.add_column(sa.Column('date_registered', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        
        batch_op.alter_column('username',
                              existing_type=sa.VARCHAR(length=80),
                              type_=sa.String(length=64),
                              existing_nullable=False)
        batch_op.alter_column('password_hash',
                              existing_type=sa.VARCHAR(length=256),
                              nullable=True) # Nota: password_hash está se tornando nullable=True
        batch_op.drop_column('created_at') # Nota: a coluna created_at está sendo removida


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('last_login')
        batch_op.drop_column('date_registered')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
