"""Adiciona tabela Condominio

Revision ID: fc78a162677a
Revises: 
Create Date: 2025-05-29 13:51:54.573701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc78a162677a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condominio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_condominio_nome'), ['nome'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_condominio_nome'))

    op.drop_table('condominio')
    # ### end Alembic commands ###
