from .user import User
from .colaborador import Colaborador
from .condominio import Condominio
from .ronda import Ronda
from .processing_history import ProcessingHistory
from .escala_mensal import EscalaMensal
from .ocorrencia_tipo import OcorrenciaTipo
from .orgao_publico import OrgaoPublico
from .logradouro import Logradouro
from .ocorrencia import Ocorrencia
from .login_history import LoginHistory
from .vw_ocorrencias_detalhadas import VWOcorrenciasDetalhadas 