"""add tabela logradouro e campo opcional logradouro_id em ocorrencia

Revision ID: 2e39b7a1bb6e
Revises: dc0697d2a16b
Create Date: 2025-07-22 01:28:49.842365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e39b7a1bb6e'
down_revision = 'dc0697d2a16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logradouro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logradouro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logradouro_nome'), ['nome'], unique=True)

    with op.batch_alter_table('escala_mensal', schema=None) as batch_op:
        batch_op.drop_constraint('_ano_mes_turno_uc', type_='unique')
        batch_op.create_unique_constraint('uq_escala_mes_turno', ['ano', 'mes', 'nome_turno'])

    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logradouro_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'logradouro', ['logradouro_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('logradouro_id')

    with op.batch_alter_table('escala_mensal', schema=None) as batch_op:
        batch_op.drop_constraint('uq_escala_mes_turno', type_='unique')
        batch_op.create_unique_constraint('_ano_mes_turno_uc', ['ano', 'mes', 'nome_turno'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('logradouro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logradouro_nome'))

    op.drop_table('logradouro')
    # ### end Alembic commands ###
