"""add exportado to ronda_esporadica

Revision ID: 4bfa95430963
Revises: 581952ff8d42
Create Date: 2025-08-02 18:11:32.306112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfa95430963'
down_revision = '581952ff8d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda_esporadica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exportado', sa.Boolean(), nullable=True))
    op.execute('UPDATE ronda_esporadica SET exportado = FALSE WHERE exportado IS NULL;')
    with op.batch_alter_table('ronda_esporadica', schema=None) as batch_op:
        batch_op.alter_column('exportado', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda_esporadica', schema=None) as batch_op:
        batch_op.drop_column('exportado')

    # Remover criação de views/tabelas já existentes
    # op.drop_table('vw_ocorrencias_detalhadas')
    # op.drop_table('vw_logradouros')
    # op.drop_table('vw_colaboradores')
    # ### end Alembic commands ###
