"""fix_ronda_esporadica_table_structure

Revision ID: 581952ff8d42
Revises: 2efe6c34fc62
Create Date: 2025-08-02 16:07:58.822167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581952ff8d42'
down_revision = '2efe6c34fc62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removendo criação de views que já existem
    # op.create_table('vw_colaboradores', ...)
    # op.create_table('vw_logradouros', ...)
    # op.create_table('vw_ocorrencias_detalhadas', ...)
    # with op.batch_alter_table('colaborador', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('nome_completo',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=150),
    #            nullable=False)
    #     batch_op.alter_column('cargo',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=100),
    #            nullable=False)
    #     batch_op.alter_column('matricula',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    #     batch_op.alter_column('data_admissao',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Date(),
    #            existing_nullable=True)
    #     batch_op.alter_column('status',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=20),
    #            nullable=False)
    #     batch_op.alter_column('data_criacao',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    #     batch_op.alter_column('data_modificacao',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    #     batch_op.create_index(batch_op.f('ix_colaborador_cargo'), ['cargo'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_colaborador_matricula'), ['matricula'], unique=True)
    #     batch_op.create_index(batch_op.f('ix_colaborador_nome_completo'), ['nome_completo'], unique=False)

    # with op.batch_alter_table('condominio', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('nome',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=150),
    #            nullable=False)
    #     batch_op.create_index(batch_op.f('ix_condominio_nome'), ['nome'], unique=True)

    # with op.batch_alter_table('escala_mensal', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('ano',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.alter_column('mes',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.alter_column('nome_turno',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=50),
    #            nullable=False)
    #     batch_op.alter_column('supervisor_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.create_index(batch_op.f('ix_escala_mensal_ano'), ['ano'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_escala_mensal_mes'), ['mes'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_escala_mensal_nome_turno'), ['nome_turno'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_escala_mensal_supervisor_id'), ['supervisor_id'], unique=False)
    #     batch_op.create_unique_constraint('uq_escala_mes_turno', ['ano', 'mes', 'nome_turno'])
    #     batch_op.create_foreign_key(None, 'user', ['supervisor_id'], ['id'])

    # with op.batch_alter_table('gemini_usage_logs', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    #     batch_op.alter_column('username',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=80),
    #            existing_nullable=True)
    #     batch_op.alter_column('api_key_name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=50),
    #            nullable=False)
    #     batch_op.alter_column('service_name',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=100),
    #            nullable=False)
    #     batch_op.alter_column('prompt_length',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    #     batch_op.alter_column('response_length',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    #     batch_op.alter_column('cache_hit',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    #     batch_op.alter_column('success',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Boolean(),
    #            existing_nullable=True)
    #     batch_op.alter_column('ip_address',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=45),
    #            existing_nullable=True)
    #     batch_op.alter_column('created_at',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    #     batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # with op.batch_alter_table('login_history', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    #     batch_op.alter_column('attempted_username',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=120),
    #            nullable=False)
    #     batch_op.alter_column('timestamp',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(timezone=True),
    #            nullable=False)
    #     batch_op.alter_column('success',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Boolean(),
    #            nullable=False)
    #     batch_op.alter_column('ip_address',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=45),
    #            existing_nullable=True)
    #     batch_op.alter_column('user_agent',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=256),
    #            existing_nullable=True)
    #     batch_op.alter_column('failure_reason',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)
    #     batch_op.create_index(batch_op.f('ix_login_history_timestamp'), ['timestamp'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_login_history_user_id'), ['user_id'], unique=False)
    #     batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # with op.batch_alter_table('logradouro', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('nome',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=150),
    #            nullable=False)
    #     batch_op.create_index(batch_op.f('ix_logradouro_nome'), ['nome'], unique=True)

    # with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('relatorio_final',
    #            existing_type=sa.TEXT(),
    #            nullable=False)
    #     batch_op.alter_column('data_hora_ocorrencia',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(timezone=True),
    #            nullable=False)
    #     batch_op.alter_column('turno',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=50),
    #            existing_nullable=True)
    #     batch_op.alter_column('status',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=50),
    #            nullable=False)
    #     batch_op.alter_column('endereco_especifico',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    #     batch_op.alter_column('logradouro_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    #     batch_op.alter_column('data_criacao',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    #     batch_op.alter_column('data_modificacao',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    #     batch_op.alter_column('condominio_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    #     batch_op.alter_column('ocorrencia_tipo_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.alter_column('registrado_por_user_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.alter_column('supervisor_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
    #     batch_op.create_index(batch_op.f('ix_ocorrencia_condominio_id'), ['condominio_id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ocorrencia_data_hora_ocorrencia'), ['data_hora_ocorrencia'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ocorrencia_ocorrencia_tipo_id'), ['ocorrencia_tipo_id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ocorrencia_registrado_por_user_id'), ['registrado_por_user_id'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ocorrencia_status'), ['status'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_ocorrencia_supervisor_id'), ['supervisor_id'], unique=False)
    #     batch_op.create_foreign_key('fk_ocorrencia_supervisor_id', 'user', ['supervisor_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'ocorrencia_tipo', ['ocorrencia_tipo_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'user', ['registrado_por_user_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'condominio', ['condominio_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'logradouro', ['logradouro_id'], ['id'])

    # with op.batch_alter_table('ocorrencia_colaboradores', schema=None) as batch_op:
    #     batch_op.alter_column('ocorrencia_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.alter_column('colaborador_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.create_foreign_key(None, 'colaborador', ['colaborador_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'ocorrencia', ['ocorrencia_id'], ['id'])

    # with op.batch_alter_table('ocorrencia_orgaos', schema=None) as batch_op:
    #     batch_op.alter_column('ocorrencia_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.alter_column('orgao_publico_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.create_foreign_key(None, 'orgao_publico', ['orgao_publico_id'], ['id'])
    #     batch_op.create_foreign_key(None, 'ocorrencia', ['ocorrencia_id'], ['id'])

    # with op.batch_alter_table('ocorrencia_tipo', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('nome',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=100),
    #            nullable=False)
    #     batch_op.alter_column('descricao',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    #     batch_op.create_index(batch_op.f('ix_ocorrencia_tipo_nome'), ['nome'], unique=True)

    # with op.batch_alter_table('orgao_publico', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('nome',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=100),
    #            nullable=False)
    #     batch_op.alter_column('contato',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=100),
    #            existing_nullable=True)
    #     batch_op.create_index(batch_op.f('ix_orgao_publico_nome'), ['nome'], unique=True)

    # with op.batch_alter_table('processing_history', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('user_id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False)
    #     batch_op.alter_column('processing_type',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=50),
    #            nullable=False)
    #     batch_op.alter_column('timestamp',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(timezone=True),
    #            nullable=False)
    #     batch_op.alter_column('success',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Boolean(),
    #            nullable=False)
    #     batch_op.alter_column('error_message',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=255),
    #            existing_nullable=True)
    #     batch_op.create_index(batch_op.f('ix_processing_history_processing_type'), ['processing_type'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_processing_history_timestamp'), ['timestamp'], unique=False)
    #     batch_op.create_index(batch_op.f('ix_processing_history_user_id'), ['user_id'], unique=False)
    #     batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('data_hora_inicio',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.alter_column('data_hora_fim',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('log_ronda_bruto',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('condominio_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('supervisor_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('turno_ronda',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('escala_plantao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('data_plantao_ronda',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('total_rondas_no_log',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('primeiro_evento_log_dt',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('ultimo_evento_log_dt',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('duracao_total_rondas_minutos',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        # batch_op.create_index(batch_op.f('ix_ronda_condominio_id'), ['condominio_id'], unique=False)
        # batch_op.create_index(batch_op.f('ix_ronda_data_plantao_ronda'), ['data_plantao_ronda'], unique=False)
        # batch_op.create_index(batch_op.f('ix_ronda_supervisor_id'), ['supervisor_id'], unique=False)
        # batch_op.create_index(batch_op.f('ix_ronda_turno_ronda'), ['turno_ronda'], unique=False)
        # batch_op.create_index(batch_op.f('ix_ronda_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ronda_esporadica', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('condominio_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('supervisor_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('data_plantao',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('escala_plantao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('turno',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('hora_entrada',
               existing_type=sa.TEXT(),
               type_=sa.Time(),
               nullable=False)
        batch_op.alter_column('hora_saida',
               existing_type=sa.TEXT(),
               type_=sa.Time(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('duracao_minutos',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('total_rondas',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('data_criacao',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('data_modificacao',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        # batch_op.create_index(batch_op.f('ix_ronda_esporadica_condominio_id'), ['condominio_id'], unique=False)
        # batch_op.create_index(batch_op.f('ix_ronda_esporadica_data_plantao'), ['data_plantao'], unique=False)
        # batch_op.create_index(batch_op.f('ix_ronda_esporadica_status'), ['status'], unique=False)
        # batch_op.create_index(batch_op.f('ix_ronda_esporadica_supervisor_id'), ['supervisor_id'], unique=False)
        # batch_op.create_index(batch_op.f('ix_ronda_esporadica_user_id'), ['user_id'], unique=False)
        # batch_op.create_foreign_key(None, 'user', ['supervisor_id'], ['id'])
        # batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        # batch_op.create_foreign_key(None, 'condominio', ['condominio_id'], ['id'])

    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.alter_column('id',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Integer(),
    #            nullable=False,
    #            autoincrement=True)
    #     batch_op.alter_column('username',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=100),
    #            nullable=False)
    #     batch_op.alter_column('email',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=120),
    #            nullable=False)
    #     batch_op.alter_column('password_hash',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=256),
    #            existing_nullable=True)
    #     batch_op.alter_column('is_approved',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Boolean(),
    #            nullable=False)
    #     batch_op.alter_column('is_admin',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Boolean(),
    #            nullable=False)
    #     batch_op.alter_column('is_supervisor',
    #            existing_type=sa.TEXT(),
    #            type_=sa.Boolean(),
    #            nullable=False)
    #     batch_op.alter_column('date_registered',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    #     batch_op.alter_column('last_login',
    #            existing_type=sa.TEXT(),
    #            type_=sa.DateTime(timezone=True),
    #            existing_nullable=True)
    #     batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
    #     batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('date_registered',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('is_supervisor',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('is_approved',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ronda_esporadica', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_user_id'))
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_status'))
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_data_plantao'))
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_condominio_id'))
        batch_op.alter_column('data_modificacao',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('total_rondas',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('duracao_minutos',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('hora_saida',
               existing_type=sa.Time(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('hora_entrada',
               existing_type=sa.Time(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('turno',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('escala_plantao',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('data_plantao',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('supervisor_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('condominio_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ronda_criador_id', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_ronda_supervisor_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ronda_user_id'))
        batch_op.drop_index(batch_op.f('ix_ronda_turno_ronda'))
        batch_op.drop_index(batch_op.f('ix_ronda_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_ronda_data_plantao_ronda'))
        batch_op.drop_index(batch_op.f('ix_ronda_condominio_id'))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('duracao_total_rondas_minutos',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ultimo_evento_log_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('primeiro_evento_log_dt',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('total_rondas_no_log',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('data_plantao_ronda',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('escala_plantao',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('turno_ronda',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('supervisor_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('condominio_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('log_ronda_bruto',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('data_hora_fim',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('data_hora_inicio',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('processing_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_processing_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_processing_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_processing_history_processing_type'))
        batch_op.alter_column('error_message',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('success',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('processing_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('orgao_publico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orgao_publico_nome'))
        batch_op.alter_column('contato',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ocorrencia_tipo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocorrencia_tipo_nome'))
        batch_op.alter_column('descricao',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('ocorrencia_orgaos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('orgao_publico_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ocorrencia_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('ocorrencia_colaboradores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('colaborador_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ocorrencia_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_ocorrencia_supervisor_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ocorrencia_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_status'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_registrado_por_user_id'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_ocorrencia_tipo_id'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_data_hora_ocorrencia'))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_condominio_id'))
        batch_op.alter_column('supervisor_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('registrado_por_user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ocorrencia_tipo_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('condominio_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('data_modificacao',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('data_criacao',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('logradouro_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('endereco_especifico',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('turno',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('data_hora_ocorrencia',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('relatorio_final',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('logradouro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logradouro_nome'))
        batch_op.alter_column('nome',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_login_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_login_history_timestamp'))
        batch_op.alter_column('failure_reason',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('success',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('attempted_username',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('gemini_usage_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('success',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cache_hit',
               existing_type=sa.Boolean(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('response_length',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('prompt_length',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('service_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('api_key_name',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('escala_mensal', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_escala_mes_turno', type_='unique')
        batch_op.drop_index(batch_op.f('ix_escala_mensal_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_escala_mensal_nome_turno'))
        batch_op.drop_index(batch_op.f('ix_escala_mensal_mes'))
        batch_op.drop_index(batch_op.f('ix_escala_mensal_ano'))
        batch_op.alter_column('supervisor_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('nome_turno',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('mes',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ano',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_condominio_nome'))
        batch_op.alter_column('nome',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               nullable=True,
               autoincrement=True)

    # with op.batch_alter_table('colaborador', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_colaborador_nome_completo'))
    #     batch_op.drop_index(batch_op.f('ix_colaborador_matricula'))
    #     batch_op.drop_index(batch_op.f('ix_colaborador_cargo'))
    #     batch_op.alter_column('data_modificacao',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    #     batch_op.alter_column('data_criacao',
    #            existing_type=sa.DateTime(timezone=True),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    #     batch_op.alter_column('status',
    #            existing_type=sa.String(length=20),
    #            type_=sa.TEXT(),
    #            nullable=True)
    #     batch_op.alter_column('data_admissao',
    #            existing_type=sa.Date(),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    #     batch_op.alter_column('matricula',
    #            existing_type=sa.String(length=50),
    #            type_=sa.TEXT(),
    #            existing_nullable=True)
    #     batch_op.alter_column('cargo',
    #            existing_type=sa.String(length=100),
    #            type_=sa.TEXT(),
    #            nullable=True)
    #     batch_op.alter_column('nome_completo',
    #            existing_type=sa.String(length=150),
    #            type_=sa.TEXT(),
    #            nullable=True)
    #     batch_op.alter_column('id',
    #            existing_type=sa.Integer(),
    #            type_=sa.TEXT(),
    #            nullable=True,
    #            autoincrement=True)

    op.drop_table('vw_ocorrencias_detalhadas')
    op.drop_table('vw_logradouros')
    op.drop_table('vw_colaboradores')
    # ### end Alembic commands ###
