"""add status to ronda

Revision ID: 6ee60b876733
Revises: efeb026e6ecb
Create Date: 2026-02-19 13:42:31.469984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ee60b876733'
down_revision = 'efeb026e6ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually cleaned to only add status to ronda, avoiding conflicts with existing views/tables
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True, server_default='Agendada'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ronda', schema=None) as batch_op:
        batch_op.drop_column('status')
    # ### end Alembic commands ###
