"""add missing boolean and timestamps

Revision ID: 6fd01c939d2f
Revises: 82bc4c5a4b7c
Create Date: 2026-02-21 19:46:39.453630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd01c939d2f'
down_revision = '82bc4c5a4b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('user', sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False))
    # op.add_column('whatsapp_message', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_message', 'created_at')
    op.drop_column('user', 'is_approved')
    # ### end Alembic commands ###
