"""add missing boolean and timestamps

Revision ID: 6fd01c939d2f
Revises: 82bc4c5a4b7c
Create Date: 2026-02-21 19:46:39.453630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd01c939d2f'
down_revision = '82bc4c5a4b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vw_colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vw_logradouros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('is_approved', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('whatsapp_message', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_table('vw_ocorrencias_detalhadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_ocorrencia', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('endereco_especifico', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('condominio', sa.String(), nullable=True),
    sa.Column('registrado_por', sa.String(), nullable=True),
    sa.Column('supervisor', sa.String(), nullable=True),
    sa.Column('relatorio_final', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vw_rondas_detalhadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('condominio_nome', sa.String(), nullable=True),
    sa.Column('condominio_endereco', sa.String(), nullable=True),
    sa.Column('user_nome', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('user_username', sa.String(), nullable=True),
    sa.Column('supervisor_nome', sa.String(), nullable=True),
    sa.Column('supervisor_email', sa.String(), nullable=True),
    sa.Column('supervisor_username', sa.String(), nullable=True),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=True),
    sa.Column('data_plantao_ronda', sa.Date(), nullable=True),
    sa.Column('turno_ronda', sa.String(), nullable=True),
    sa.Column('escala_plantao', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('total_rondas_no_log', sa.Integer(), nullable=True),
    sa.Column('duracao_total_rondas_minutos', sa.Integer(), nullable=True),
    sa.Column('primeiro_evento_log_dt', sa.DateTime(), nullable=True),
    sa.Column('ultimo_evento_log_dt', sa.DateTime(), nullable=True),
    sa.Column('relatorio_processado', sa.Text(), nullable=True),
    sa.Column('log_ronda_bruto', sa.Text(), nullable=True),
    sa.Column('duracao_horas', sa.Float(), nullable=True),
    sa.Column('status_ronda', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vw_rondas_detalhadas')
    op.drop_table('vw_ocorrencias_detalhadas')
    op.drop_table('vw_logradouros')
    op.drop_table('vw_colaboradores')
    op.drop_column('whatsapp_message', 'created_at')
    op.drop_column('user', 'is_approved')
    # ### end Alembic commands ###
