"""Adicionar view vw_rondas_detalhadas

Revision ID: 7eac948b9e42
Revises: ee5fec371d93
Create Date: 2025-08-04 23:01:24.381564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eac948b9e42'
down_revision = 'ee5fec371d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Apenas criar a view vw_rondas_detalhadas, as outras views já existem
    op.execute("""
        CREATE OR REPLACE VIEW vw_rondas_detalhadas AS
        SELECT 
            r.id,
            r.condominio_id,
            r.user_id,
            r.supervisor_id,
            c.nome as condominio_nome,
            NULL as condominio_endereco,
            u.username as user_username,
            u.email as user_email,
            u.username as user_nome,
            s.username as supervisor_username,
            s.email as supervisor_email,
            s.username as supervisor_nome,
            r.data_hora_inicio,
            r.data_hora_fim,
            r.data_plantao_ronda,
            r.turno_ronda,
            r.escala_plantao,
            r.tipo,
            r.total_rondas_no_log,
            r.duracao_total_rondas_minutos,
            r.primeiro_evento_log_dt,
            r.ultimo_evento_log_dt,
            r.relatorio_processado,
            r.log_ronda_bruto,
            CASE 
                WHEN r.duracao_total_rondas_minutos IS NOT NULL 
                THEN r.duracao_total_rondas_minutos / 60.0 
                ELSE NULL 
            END as duracao_horas,
            CASE 
                WHEN r.data_hora_fim IS NULL THEN 'em_andamento'
                WHEN r.data_hora_fim IS NOT NULL THEN 'finalizada'
                ELSE 'cancelada'
            END as status_ronda
        FROM ronda r
        LEFT JOIN condominio c ON r.condominio_id = c.id
        LEFT JOIN "user" u ON r.user_id = u.id
        LEFT JOIN "user" s ON r.supervisor_id = s.id
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS vw_rondas_detalhadas")
    # ### end Alembic commands ###
