"""Add WhatsAppMessage and Condominio.whatsapp_group_id

Revision ID: 82bc4c5a4b7c
Revises: 6ee60b876733
Create Date: 2026-02-20 10:22:23.943056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82bc4c5a4b7c'
down_revision = '6ee60b876733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=150), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('remote_jid', sa.String(length=100), nullable=False),
    sa.Column('participant_jid', sa.String(length=100), nullable=False),
    sa.Column('push_name', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominio.id'], name='fk_whatsapp_msg_condominio_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whatsapp_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_message_condominio_id'), ['condominio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_message_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_whatsapp_message_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('ronda_esporadica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_condominio_id'))
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_data_plantao'))
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_status'))
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_supervisor_id'))
        batch_op.drop_index(batch_op.f('ix_ronda_esporadica_user_id'))

    op.drop_table('ronda_esporadica')
    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_group_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_condominio_whatsapp_group_id'), ['whatsapp_group_id'], unique=False)

    with op.batch_alter_table('processing_history', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_history', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_condominio_whatsapp_group_id'))
        batch_op.drop_column('whatsapp_group_id')

    op.create_table('ronda_esporadica',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('condominio_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_plantao', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('escala_plantao', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('turno', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hora_entrada', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('hora_saida', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('log_bruto', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('relatorio_processado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('duracao_minutos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_rondas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_criacao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('data_modificacao', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('exportado', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominio.id'], name=op.f('ronda_esporadica_condominio_id_fkey')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], name=op.f('ronda_esporadica_supervisor_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('ronda_esporadica_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ronda_esporadica_pkey'))
    )
    with op.batch_alter_table('ronda_esporadica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ronda_esporadica_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ronda_esporadica_supervisor_id'), ['supervisor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ronda_esporadica_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ronda_esporadica_data_plantao'), ['data_plantao'], unique=False)
        batch_op.create_index(batch_op.f('ix_ronda_esporadica_condominio_id'), ['condominio_id'], unique=False)

    with op.batch_alter_table('whatsapp_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_message_timestamp'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_message_message_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_message_condominio_id'))

    op.drop_table('whatsapp_message')
    # ### end Alembic commands ###
