"""add ronda_esporadica table

Revision ID: add_ronda_esporadica_table
Revises: dc0697d2a16b
Create Date: 2025-01-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_ronda_esporadica_table'
down_revision = 'dc0697d2a16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ronda_esporadica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condominio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('data_plantao', sa.Date(), nullable=False),
    sa.Column('escala_plantao', sa.String(length=100), nullable=False),
    sa.Column('turno', sa.String(length=50), nullable=True),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_saida', sa.Time(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('log_bruto', sa.Text(), nullable=True),
    sa.Column('relatorio_processado', sa.Text(), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('total_rondas', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_modificacao', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['condominio_id'], ['condominio.id'], ),
    sa.ForeignKeyConstraint(['supervisor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ronda_esporadica_condominio_id'), 'ronda_esporadica', ['condominio_id'], unique=False)
    op.create_index(op.f('ix_ronda_esporadica_data_plantao'), 'ronda_esporadica', ['data_plantao'], unique=False)
    op.create_index(op.f('ix_ronda_esporadica_status'), 'ronda_esporadica', ['status'], unique=False)
    op.create_index(op.f('ix_ronda_esporadica_supervisor_id'), 'ronda_esporadica', ['supervisor_id'], unique=False)
    op.create_index(op.f('ix_ronda_esporadica_user_id'), 'ronda_esporadica', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ronda_esporadica_user_id'), table_name='ronda_esporadica')
    op.drop_index(op.f('ix_ronda_esporadica_supervisor_id'), table_name='ronda_esporadica')
    op.drop_index(op.f('ix_ronda_esporadica_status'), table_name='ronda_esporadica')
    op.drop_index(op.f('ix_ronda_esporadica_data_plantao'), table_name='ronda_esporadica')
    op.drop_index(op.f('ix_ronda_esporadica_condominio_id'), table_name='ronda_esporadica')
    op.drop_table('ronda_esporadica')
    # ### end Alembic commands ### 