"""add tipo field to ronda table

Revision ID: add_tipo_field_to_ronda
Revises: add_ronda_esporadica_table
Create Date: 2025-01-30 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_tipo_field_to_ronda'
down_revision = 'add_ronda_esporadica_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ronda', sa.Column('tipo', sa.String(length=50), nullable=True, server_default='tradicional'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ronda', 'tipo')
    # ### end Alembic commands ### 