"""Adiciona campo turno a ocorrencia

Revision ID: c69d0ffcff85
Revises: 2de62aff61c0
Create Date: 2025-07-02 11:49:38.819382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c69d0ffcff85'
down_revision = '2de62aff61c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora_ocorrencia', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('turno', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_modificacao', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_ocorrencia_data_ocorrencia')
        batch_op.create_index(batch_op.f('ix_ocorrencia_data_hora_ocorrencia'), ['data_hora_ocorrencia'], unique=False)
        batch_op.drop_column('data_ocorrencia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_ocorrencia', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_ocorrencia_data_hora_ocorrencia'))
        batch_op.create_index('ix_ocorrencia_data_ocorrencia', ['data_ocorrencia'], unique=False)
        batch_op.drop_column('data_modificacao')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('turno')
        batch_op.drop_column('data_hora_ocorrencia')

    # ### end Alembic commands ###
