"""aumentar_campo_error_message_para_1000_chars

Revision ID: efeb026e6ecb
Revises: merge_multiple_heads
Create Date: 2025-09-26 00:37:17.175581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'efeb026e6ecb'
down_revision = 'merge_multiple_heads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_history', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processing_history', schema=None) as batch_op:
        batch_op.alter_column('error_message',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
